refactor: do not use watch mode for worker mode

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -41,7 +41,18 @@ jobs:
           # Bazelisk will download bazel to here
           XDG_CACHE_HOME: ~/.cache/bazel-repo
         run: |
+          set -e
           npm pack
           cd e2e
           npm install $(find ../ -name 'aspect-build-webpack*.tgz') --save-dev
+          bazel --bazelrc=../.github/workflows/ci.bazelrc --bazelrc=../.bazelrc test //...
+          # make sure that webpack in worker mode builds in subsequent invocations.
+          echo console.log\(\"$(date)\"\) > ./test/module.js
+          if bazel test //...; then 
+              echo "###########################"
+              echo "expected bazel test to fail but it didn't"
+              exit 1
+          fi
+          # now update check-in files for tests to pass
+          bazel --bazelrc=../.github/workflows/ci.bazelrc --bazelrc=../.bazelrc run //test:update
           bazel --bazelrc=../.github/workflows/ci.bazelrc --bazelrc=../.bazelrc test //...
